//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.269.
// 
#pragma warning disable 1591

namespace goodmanwebsite.bluearc {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="IntegrationServicesSoap", Namespace="http://www.goodman.com/")]
    public partial class IntegrationServices : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetBBXtrasOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetActivePropertiesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public IntegrationServices() {
            this.Url = global::goodmanwebsite.Properties.Settings.Default.goodmanwebsite_bluearc_IntegrationServices;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetBBXtrasCompletedEventHandler GetBBXtrasCompleted;
        
        /// <remarks/>
        public event GetActivePropertiesCompletedEventHandler GetActivePropertiesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.goodman.com/GetBBXtras", RequestNamespace="http://www.goodman.com/", ResponseNamespace="http://www.goodman.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetBBXtras(string countrycode) {
            object[] results = this.Invoke("GetBBXtras", new object[] {
                        countrycode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetBBXtrasAsync(string countrycode) {
            this.GetBBXtrasAsync(countrycode, null);
        }
        
        /// <remarks/>
        public void GetBBXtrasAsync(string countrycode, object userState) {
            if ((this.GetBBXtrasOperationCompleted == null)) {
                this.GetBBXtrasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBBXtrasOperationCompleted);
            }
            this.InvokeAsync("GetBBXtras", new object[] {
                        countrycode}, this.GetBBXtrasOperationCompleted, userState);
        }
        
        private void OnGetBBXtrasOperationCompleted(object arg) {
            if ((this.GetBBXtrasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBBXtrasCompleted(this, new GetBBXtrasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.goodman.com/GetActiveProperties", RequestNamespace="http://www.goodman.com/", ResponseNamespace="http://www.goodman.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetActiveProperties(string countrycode) {
            object[] results = this.Invoke("GetActiveProperties", new object[] {
                        countrycode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetActivePropertiesAsync(string countrycode) {
            this.GetActivePropertiesAsync(countrycode, null);
        }
        
        /// <remarks/>
        public void GetActivePropertiesAsync(string countrycode, object userState) {
            if ((this.GetActivePropertiesOperationCompleted == null)) {
                this.GetActivePropertiesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetActivePropertiesOperationCompleted);
            }
            this.InvokeAsync("GetActiveProperties", new object[] {
                        countrycode}, this.GetActivePropertiesOperationCompleted, userState);
        }
        
        private void OnGetActivePropertiesOperationCompleted(object arg) {
            if ((this.GetActivePropertiesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetActivePropertiesCompleted(this, new GetActivePropertiesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetBBXtrasCompletedEventHandler(object sender, GetBBXtrasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBBXtrasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBBXtrasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetActivePropertiesCompletedEventHandler(object sender, GetActivePropertiesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetActivePropertiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetActivePropertiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591